server:
  port: 7001
  servlet:
    context-path: /ad-search
spring:
  application:
    name: eureka-client-ad-search
  jpa:  # jpa的配置
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/ad_data?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2 # 默认初始化2个连接
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
feign:  # Feign的配置
  hystrix:
    enabled: true
management: # 监控
  endpoints:
    web:
      exposure:
        include: "*"

# BinLog的Client配置
adconf:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: root
    binlogName: ""
    positiion: -1

  kafka:
    topic: ad-search-mysql-data


