server:
  port: 9000
spring:
  application:
    name: ad-gateway
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/
zuul:
  # 统一前缀
  prefix: /codezp
  routes:
    sponsor:
      path: /ad-sponsor/**
      serviceId: eureka-client-ad-sponsor
      # 不跳过前缀 如：127.0.0.1:9000/codezp/ad-sponsor/create/adPlan 如果为true就会转发/create/adPlan，但是我们的请求都是有/ad-sponsor前缀的，所以会报错
      strip-prefix: false
    search:
      path: /ad-search/**
      serviceId: eureka-client-ad-search
      strip-prefix: false
